server:
  port: 8081
  shutdown: graceful
  banner:
    charset: UTF-8
    location: classpath:banner.txt

logging:
  level:
    root: info

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  profiles:
    active: dev